# Netlify configuration for Timepass Katta App

# This redirect is a proxy to Firebase Storage to avoid CORS errors
# when drawing images to a canvas on the live site.
[[redirects]]
  from = "/api/images/*"
  to = "https://firebasestorage.googleapis.com/:splat"
  status = 200

# These headers are CRITICAL for FFMPEG (video processing) to work.
# They enable the SharedArrayBuffer feature in modern browsers.
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
